chain_one_line_max = 80
closure_block_indent_threshold = -1
condense_wildcard_suffixes = true
error_on_line_overflow = false
max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
take_source_hints = true
where_style = "Legacy"
wrap_comments = true
fn_args_layout = "Visual"
